# shellcheck shell=bash
# proxy/lib/sync.sh — multi-device settings sync (the proxy-side twin of the
# parent repo's `scripts secret push/pull`).
#
# What is synced: merge.yaml, regions.conf, subs.conf, and the *portable* keys
# of proxy.conf (active_sub, sub_ua, sub_url, region_*, test_*). These are the
# user's assets: prepend rules, region groups, subscriptions (with tokens).
#
# What is NOT synced (per-machine by design):
#   - config.yaml / .bak      regenerated by each machine's sub refresh
#   - bin / install_method    binary paths differ per machine
#   - controller / secret     tied to each machine's local config state
#   - node_group / selected node — the chosen node is runtime-only memory in
#     the running core (resets on restart) and is intentionally per-machine:
#     each machine is in a different location and should pick its own exit.
#   - env.state / mihomo.log / ui/  runtime state
#
#   proxy sync export [path]      bundle to stdout or a .tar.gz file
#   proxy sync import [path]      apply a bundle (file, dir, or stdin)
#   proxy sync push <user@host>   transfer + merge on the remote (bash/awk only)
#   proxy sync pull <user@host>   fetch the remote's bundle and import locally

SYNC_CONF_KEYS="active_sub sub_ua sub_url region_interval region_url region_exclude test_timeout test_url lan pool"

# filter proxy.conf: print only the portable keys (space-separated list in $1)
_sync_portable() { # <file> <keys>
    awk -F= -v ks="$2" 'BEGIN{split(ks,k," ")} {for(i in k) if($1==k[i]) print}' "$1" 2>/dev/null
}

# merge a proxy.portable file into the local proxy.conf: keep device-specific
# keys, let the bundle's portable keys win.
_sync_merge_conf() { # <portable-file>
    local keys=$SYNC_CONF_KEYS
    { grep -vE "^(${keys// /|})=" "$PROXY_CONF" 2>/dev/null || true; cat "$1"; } > "$PROXY_CONF.new"
    mv -f "$PROXY_CONF.new" "$PROXY_CONF"; chmod 600 "$PROXY_CONF"
}

sync_cmd() {
    local sub=${1:-}; shift || true
    case "$sub" in
        export) sync_export "$@" ;;
        import) sync_import "$@" ;;
        push)   sync_push "$@" ;;
        pull)   sync_pull "$@" ;;
        -h|--help|"")
            say "用法: proxy sync export [path] | import [path] | push <user@host> | pull <user@host>"
            say ""
            say "多端同步 (对标 scripts secret push/pull)。同步: merge.yaml + regions.conf +"
            say "subs.conf + proxy.conf 可迁移键 (active_sub/sub_ua/sub_url/region_*/test_*)。"
            say "  export [path]   打包到文件 (省略=输出到 stdout)"
            say "  import [path]   应用打包内容 (文件/目录/省略=stdin)"
            say "  push <user@host> 经 ssh 推送到远端并自动合并 (远端无需装 proxy)"
            say "  pull <user@host> 从远端拉取并应用到本机"
            say "不同步 (每台机器独立): config.yaml / bin / controller / secret / 节点选择"
            ;;
        *) die "proxy sync: 未知子命令 $sub" ;;
    esac
}

# build a bundle dir with merge.yaml/regions.conf/subs.conf/proxy.portable
_sync_build() { # <dest-dir>
    local tmp=$1
    for f in merge.yaml regions.conf subs.conf; do
        [[ -f "$CONF_DIR/$f" ]] && cp -f "$CONF_DIR/$f" "$tmp/$f"
    done
    _sync_portable "$PROXY_CONF" "$SYNC_CONF_KEYS" > "$tmp/proxy.portable"
    if ! ls "$tmp"/merge.yaml "$tmp"/regions.conf "$tmp"/subs.conf "$tmp"/proxy.portable >/dev/null 2>&1 \
       && [[ ! -s "$tmp/proxy.portable" ]]; then
        warn "本机无可同步配置 (无 merge/region/订阅)"
        return 1
    fi
}

sync_export() { # [path] — bundle to file, or stdout
    local tmp; tmp=$(mktemp -d)
    trap 'rm -rf "$tmp"' RETURN
    _sync_build "$tmp" || return 1
    if [[ -n "${1:-}" ]]; then
        tar czf "$1" -C "$tmp" . || die "写入失败: $1"
        chmod 600 "$1"
        ok "已导出: $1"
        sync_summary
    else
        tar czf - -C "$tmp" . || die "导出失败"
    fi
}

sync_import() { # [path] — file / dir / stdin
    local src=${1:-} tmp
    if [[ -n "$src" && -d "$src" ]]; then
        tmp=$src
    elif [[ -n "$src" && -f "$src" ]]; then
        tmp=$(mktemp -d)
        tar xzf "$src" -C "$tmp" 2>/dev/null || die "无法解压: $src"
    else
        tmp=$(mktemp -d)
        tar xzf - -C "$tmp" 2>/dev/null || die "stdin 内容不是有效打包"
    fi
    mkdir -p "$CONF_DIR"
    [[ -f "$tmp/proxy.portable" && -s "$tmp/proxy.portable" ]] || die "打包内容无效 (缺 proxy.portable)"

    # backup what we are about to replace
    local bak="$CONF_DIR/.sync-bak"; mkdir -p "$bak"
    for f in merge.yaml regions.conf subs.conf proxy.conf; do
        [[ -f "$CONF_DIR/$f" ]] && cp -f "$CONF_DIR/$f" "$bak/$f"
    done

    local n=0
    for f in merge.yaml regions.conf subs.conf; do
        if [[ -f "$tmp/$f" ]]; then
            cp -f "$tmp/$f" "$CONF_DIR/$f"; chmod 600 "$CONF_DIR/$f"; n=$((n+1))
        fi
    done
    _sync_merge_conf "$tmp/proxy.portable"
    ok "已导入 $n 个配置 + proxy.conf 可迁移键 (备份 → $bak)"

    # re-apply merge/region so prepend rules survive; sub refresh stays manual
    # (a brand-new machine may not have working network yet)
    if [[ -f "$CONF_DIR/merge.yaml" ]]; then
        # shellcheck source=merge.sh
        source "$SCRIPT_DIR/lib/merge.sh"
        if _merge_rules >/dev/null 2>&1; then
            info "重新应用 merge 规则 ..."
            merge_apply || warn "merge 应用失败 (稍后: proxy merge apply)"
        fi
    fi
    if [[ -f "$CONF_DIR/regions.conf" ]]; then
        # shellcheck source=region.sh
        source "$SCRIPT_DIR/lib/region.sh"
        if [[ -n "$(_region_names)" ]]; then
            info "重新应用 region 组 ..."
            region_apply || warn "region 组应用失败 (稍后: proxy region apply)"
        fi
    fi
    local sub; sub=$(conf_get active_sub)
    if [[ -n "$sub" ]]; then
        say "活跃订阅: $sub   →  新机器: proxy sub refresh 拉取应用"
    else
        say "未设活跃订阅 → 先: proxy sub add <name> <url>"
    fi
}

sync_push() { # <user@host>
    local host=$1
    [[ -n "$host" ]] || die "用法: proxy sync push <user@host>"
    has ssh || die "缺少依赖: ssh"
    local tmp; tmp=$(mktemp -d)
    trap 'rm -rf "$tmp"' RETURN
    _sync_build "$tmp" || return 1
    info "推送配置到 $host ..."
    # transfer + merge entirely with remote-side bash/grep/awk (no proxy CLI needed)
    tar czf - -C "$tmp" . | ssh -o ConnectTimeout=10 "$host" '
        set -e
        mkdir -p ~/.config/mihomo
        cd ~/.config/mihomo
        mkdir -p .sync-incoming
        tar xzf - -C .sync-incoming
        for f in merge.yaml regions.conf subs.conf; do
            if [ -f ".sync-incoming/$f" ]; then
                cp -f ".sync-incoming/$f" "$f"
                chmod 600 "$f" 2>/dev/null || true
            fi
        done
        if [ -s .sync-incoming/proxy.portable ]; then
            keys="active_sub sub_ua sub_url region_interval region_url region_exclude test_timeout test_url lan pool"
            { grep -vE "^(${keys// /|})=" proxy.conf 2>/dev/null || true; cat .sync-incoming/proxy.portable; } > proxy.conf.new
            mv -f proxy.conf.new proxy.conf
            chmod 600 proxy.conf
        fi
        rm -rf .sync-incoming
        echo "remote sync OK ($(hostname))"
    ' || die "ssh 推送失败"
    ok "已推送"
    sync_summary
}

sync_pull() { # <user@host>
    local host=$1
    [[ -n "$host" ]] || die "用法: proxy sync pull <user@host>"
    has ssh || die "缺少依赖: ssh"
    local tmp; tmp=$(mktemp -d)
    trap 'rm -rf "$tmp"' RETURN
    info "从 $host 拉取配置 ..."
    ssh -o ConnectTimeout=10 "$host" \
        'cd ~/.config/mihomo 2>/dev/null && tar czf - merge.yaml regions.conf subs.conf proxy.conf 2>/dev/null' \
        | tar xzf - -C "$tmp" 2>/dev/null || die "ssh 拉取失败"
    [[ -f "$tmp/proxy.conf" ]] || die "远端无 ~/.config/mihomo/proxy.conf"
    _sync_portable "$tmp/proxy.conf" "$SYNC_CONF_KEYS" > "$tmp/proxy.portable"
    rm -f "$tmp/proxy.conf"
    sync_import "$tmp"
}

sync_summary() {
    say "内容: $(ls "$CONF_DIR/merge.yaml" >/dev/null 2>&1 && echo merge ✓ || echo 'merge -')  \
$(ls "$CONF_DIR/regions.conf" >/dev/null 2>&1 && echo region ✓ || echo 'region -')  \
$(ls "$CONF_DIR/subs.conf" >/dev/null 2>&1 && echo sub ✓ || echo 'sub -')  \
$(conf_get active_sub | sed 's/^/active=/')"
}
